language: python
sudo: false
python:
- '2.7'
install:
- python setup.py install
script:
- true
deploy:
  on:
    tags: true
    all_branches: true
  provider: pypi
  user: sphemakh
  password:
    secure: a/eCphPo7FxFRjHCMT6bJmMU4csltnZSI12GovBEJPPeCChh1XoY+XkpuDuaI2lmzdvBOLazQVP2dWgqCu/v2d1cgqGEgk5wMIk/g+mu0X2vwY0vleCSFn3xeqUi2ZJqaeVCWfCY7mU4EFuDEM3WEy/AQ215xZVTmPl/YedfJAQvrDB4vct+DE14phcfoT4c+cBwOCiRygYWOXbMxtKNF79d4keyOA0OdNm18y1yTBcyvArMaDy5uvLfeirzbgwnGqbIuLhZNpjRiqB2pJZqlFaUW6bX0epQFZ8t2wZYis6E4Urbl/nlNPSiz4oJSOHbmdAAYz2sH4GBDjLpsW861kA90zkkDOJxoHaYttxsR71vIFYBkLmFyGaqktk7I1NYwpsn0wSnVIxsdET4ADY1/VPd/xXWv+TgDOKGJRvMywoOazwN8YP1EG1hNB9tzKoE6vKyXP/nABarzc1ygR9ZDGF+DSyCak6sM9piPpSCvn7cWBgiWRWNe7FFsC8WP7N7gE4umWU2L5hHJRUFh15QzlZgF0VBA0ALpPL9o0McaGVUMX0IXuusKP9tnLHY9Y9RRUhuJ2BpVozdDx30Q1UCaGmBssJNYHW2+HDz8jUDiPgw0uVBI4otBH4RVBTX8BJ1YYXo9KMDS/sPCcnj69/F3cDnvWK66XcBghtdANzxiTw=
