language: python
sudo: false
python:
- '2.7'
install:
- python setup.py install
script:
- true
deploy:
  provider: pypi
  user: sphemakh
  password:
    secure: dfZm3RX2UGwVi39TvyQZmKOuaoXclPVDHhediIIDnl+el/J1c8awztYZCVIMh9ZBxamMauJqAXcaDhh/dLNWo5GWrf3fIwAvHl3SYrCPLZY7J9XMqgJNdV75N9Gptgl2VntPA0YDo32Sl1WFN6C1/QXjSYyrZV9iuBQIwJSen1vfoXtokwM7/TJkjgupwhlulANILQkcHGqCxG/N5DjcHeJJz4QxF9Om5bpKzkIZISlOHC2f6jLHUm+MAD8ClgiyjqA5NrsIbH6V1ooWYNJlJObgrGQQZZen7u81+EF6u2zPrZBKzpj9dzYXXyG21wC0xApey7IjT9VmoF80O6l3HM3jgYdokGlKo43E87l632wHIjht2RCepAsII+u9HZHFXTj6BcjhEwhq1Mh4oyZ8owBW+cWqt/mSUcB0W1agar3Ij/QNFVBqpSlhz6hRcyKeub5DQjtbkY8EgX/x+yGcvTXXDGt5eMJ+/95DYo/RLTeCQ2Rs5XWG9SWBNvhWiOHF+5jGXo33sHooteMKWJKg1gV3lmemrYxRAiOLxUc5WwzgOa7UkAZSIc7gCrhhfbrd3KchikQv0VftRilHtzTp7JJ1UdWH329WNW5IpwDbWkrS8mpx1qBBuugKtR+0LWSGf/pGqIkj5qsmY5LK+quUbY1zutpFcdBeSQodWxzICMg=
  on:
    tags: true
