language: python
sudo: false
python:
- '2.7'
install:
- python setup.py install
script:
- true
deploy:
  provider: pypi
  user: sphemakh
  password:
    secure: mVfSAmIlbzEkylxwf5KLpvZycCIZzVOKPGbLE0ZzeanNpGBPOHjuiWCZyTRJ1jSr+J4oBW0yHV18Zlo1Xq9EQLL0Qf3VwhsJdYXDYHhNFmnEigkrCPmJuob8w7gyDECoDjoDBl5dtbYx7NawUe4Heh087j2ve/uK3CcMUf61yX3TAcLH6ww4qzdS/yPXl9vfXDkYaSnoRzDpJb8DrYkAG8qfIvUwca8WSxsJlCt2J48CfBb7pOtPnLw7qwC7Q/daR21tmxKbZm+Y4gYFJsxzf34nEpn/zVA6FlzkF1KmLZBTLDwaAGb+lBIDmIOmMCqOtcP1YQHQFvTnK28PwctAWzYA9nt+JFjgjLi5a6vnWXKE6bHaIvYgUmKuTA75UR2vBoJWzQjYzjKpQc1vckL3FV50VYqcmRy73Xr1Db89reQ9HSCfFq97Aa+mJqyFeFdg8ZWC5ST1WWpjW/B5WQpxOiWSkxAlKUHM8jOVZncJ88m80UZtd4MlROofZ82SfkhOdREWW30HRHXS5YFLuGOhmxvNhMhaUROPBwCPKsUGT1FVeX4SHi/19vuDrCfM1x2a4jyIT5Ue/+MEC+4ortP2k89Fy3sUbcN9vI3JRaceiUJCHQ1tyTu7p7n0EfIPynu8zm6CoxHxerLmmEMM014Huk4I3cK9TiIYAkr99LtqVVI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: SpheMakh/Stimela
