language: python
sudo: false
python:
- '2.7'
install:
- python setup.py install
script:
- true
deploy:
  provider: pypi
  user: sphemakh
  password:
    secure: iTBzmCDTgW478mXxrlntbtPjPcsUUszBgq/Lliy0n8chjytr2Hqzlf+aSeS3GKZMcCrdVB09xcHy5wMI5WeUpVnlB4FEuE+4vmhCFs63xfboJ8pwweFlVhC63hjloDbMLP2PR7pvHakYiXznFJQ6JOVPy0Ao+uNuNBvjd0xbbAbRM1H8KNw3wSfDyvn9BmY80j0tRuKyqSlzXBnmbMpowDihF0rEPy5wH7P5WJwr5wknqIl05LvsS0bA5ybB3lUxbHliMK8O5Xshv4LvD7bbF4w2ngNonLGi0h23RTWUubvDjsqpVBFi2wlU1Rbdz3CgSTIA3qTU5V4S2w7j6bI5CG7Rxqr3O4kaqUrK06jr/a2ay/8MgAFHgajsEDmJGmO/nZ+fOcmq9Ns5UgXawkuwHbKq7+uv/AtkcaQ5SpJawZwE68Nivuc7JNevuLQ2veq/rmSpgsmVfgrKdTWxj1xwuHrg3sMDQir2I3vtnRIXksiEczeNSmN08UUy/14PE/ofOKSsJKJTo2zFlb4DyxiJzTfCoXwld0HKEMGzpitrZ9lN0WVExS5lIvcHt4Oe/ijwu7RCOE08dlPR2HlwhCndeRJSAnJOZUXPkYdKxne2pIG9eSWXdReMGovg04H5PrF5dYxv3xhyBy1oyNNyiuOA7pucDhi4neAI3oWeUc5MZjI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: SpheMakh/Stimela
