language: python
sudo: false
python:
- '2.7'
install:
- python setup.py install
script:
- true
deploy:
  provider: pypi
  user: sphemakh
  password:
    secure: RCMkR98TvDBV4vGKdczZQPUkbQssn2LzgEHgjaZAB2aSUwbrLIHnH2pesbTg4WbQkeSoyVWrKaAcQSfGZEn67jMeUB+1lpDRXaALP0V7W6PhrZpaeHZYeM/ksWb3La06uf6PXFUHwdfHgIdJsMuPdKFW7pfEB18+SiY/Bm45NhuJRwhfUhjFtLPjybIjKOvkV97O5J168fPWmkILd9aQDuWKFoYbHLUeTU3yIM8hT/OzrUi8EVFRdXKlDyYbeSIok16mTcI8nGL7+ydcXbgtquObcpgG+Y7czCGbIYCHiCpqoMp4S3z7jVaT8dPEVucvR26JvfrIoZ1cy827an3xcniUl59Ny+2mOIuI5IMtGLkr3cRqLa+WkiqtbalMFpSYAo1gHCrbbCXlrD72G7Y7F1L3+u/9OTExANKQiyq2ostAQUA/KFfqlCtXs/vJ2Xdnkwkstncy4KZQLplIMggUMiJfdw6KxhjlCJQ7tK+xFoq4MUMYmXRdV0Av90TIIUYKM2p2OV/m5Woe8LD9ujh8XlA3RvMcoZvtBivZNkbNwFVr/KIXz29MAcQZhtu5n/gQkDZ9rW+TlNAaArES9xtPrjPgsZrgiWQVE6k5/A1qoPXv42ANNRglwAhOnsK7tQrmuYZuFo1+tZX7gpsQAAbTiOYDcX6bHZpQOWB7ciqvqNk=
  on:
    tags: true
    distributions: sdist bdist_wheel
