language: python
sudo: false
python:
- '2.7'
install:
- python setup.py install
script:
- true
deploy:
  provider: pypi
  user: sphemakh
  password: 
  secure: mLbu3Q8FQ5jBYVS31PNgP0AN44T8YFDtv36u9Em0WmevhBZsJDHhRLr+9xBqMPnERev09iF1f34M9xbSgDElLRQgQrvtmFXD1Ze+Kd9/pcYzVrFLTnTOeBH+iiXFZ6v8Zvu0AAYH2Hm2lbRMb0scVclbisdsZ53xuXMQ+fTAxE9Y1kZIsSd3tp4HnBt2STMM/VWI9Qj/5HTYkyL8kU2BU5eSeLXP+2CEdq+2+8+CXCY1b+AHiiiQq6cqvatAd47o3OTFMQE01L/g+MWR00hX9Y1YX2m/9HPTG2pgcTqhg2ckgjJgBR/aYv4AUzrOcP3nT2KDOiDK0m0cPSeESGeGxPwqmJmVWHGp+78oRCAnS09xsXHJB1sv5SoXeGwhzDhJCYr30bM8fduy1QOX2BdIuPq60dolMHF0dw8n6Se8LrhE6dKVr722vZFb9/f/ul7vPDJQ/aCzaFyo0ECyWKxpWde+3Rwt/hB4UW96QpUaKNr33QHeqnUihakzMuVhSx+R38QJGJPfsatJT5hF9INY9u/AxuJhpvfX5zG2VBHVJATQa42VhNaZWcuREkmOaAsyQgab8FRL4fQQ3pOtBP6WN2yqESIUN/S9o3avnVVaTC6aQ55J/DGmf6OYAWiwe1NolcN6ll3LTVVsM30dvcWV+dHO40LrHw6Jbn5vK2ZaKfQ=
  on:
    tags: true
env:
  global:
    secure: SozyooMPNsN4dwtIM64ZwTBzAAeito3SvSAZ3jzyoXlc0ESRdaZZSi9k3sC3n/vltTcpXNDcOMum7jBfpbKICedfe16dpnyVyu86b0DqTTDgw539I8faD4mH+wcpaaJdOHTruZ9ecPgURhASIrtB/Suv+ymbySC4rV/i3Nz7C1D1dXfGgDeRQaUnvd7D/tMBJLB3tZW/dTt3j66LkxX73VKLbB/vjp6d7wnPn/vt9T0Bt+wX4xsu/IxjjO0h7afkOI56gvXiA1KZDmoBVt+uSvGeptPzhrqaMp/1qIMXeTWJTsVw0y2OxYOYxnYfeUkf8FM1rcWnYOhjjE6SKt3uF00ZkRCRYGyb5mD0r7n7oo8R/oUkrPNed/kOFeoQX3xFWpwIe3NFPCQONzlseGirpMpAqB6uaEgHik3UnbO7GHB3YLtn5RSQYqop5bs+h/XTOTOQSHH1OQD3en3a+nlWQ93Gpoaf047kT6hUq1glE5r8YmAaUyDabtxJdCL8xL1XDqUwSbZYeVFlBMipcO73D0YtBManM7IxIkhftu5rhkj+7qfaP4odR/++sLPMLyRaj7pEEl9fgVit66TljR675ZrNZDMyiL+eUg8RwCAx4PwLyN3U0NyLOVO+S0q/EZQUFNLNBXBw3ceS8sylZZK5LgEGulwWu2eHZiXnTUN5OOM=
