language: python
sudo: false
python:
- '2.7'
install:
- python setup.py install
script:
- true
deploy:
  provider: pypi
  user: sphemakh
  password:
    secure: Y/sOKk82/5btnd2Ro1OJE3fF3Y0jhr2JZjrWQx2HV21OS/Yzjmze3boM09x2BcIywG0v5TetQ1f+T7/W22rN4RFSvuEXPYQsw5bJdug3Y96NisKZJPMtgJMUVfN6+TBiceochVVjEWPTWconQZiA9tjGLHCQQqzMsxWgup+3g0kDw2WG4by8uwc2ShHb8kUdzNqWJ/H669kogQRYZDZ1e9O9ONTNH+85pkDh59BjHS99MDHC6HGT+olNGwgRsRngHXrugi/C+vt5f3Q5g5qkFStvO0JfgY8MgeMwTAv5nA2NhD07ldqhS4y0ao1peYMgeUcqFUC0e+JQxwp72gjFFbKcCsWxz92CajWl0+xZVdV4tYt52C71xIn4kgMWxj0laGz7ZdoKj2Hac/S+HWy4SYR4kfiVMhICAPXPqtERw1Exy3N5voxAOcaTYb9mZCujtdNoHq95FlZJI3MJcMaeReFdPTPKdk6Js+M4BmlYK8CBZ9SjAG7l4I8Kq2Y/FbsnvosRF57ocC7QGqblLqbD/YtOeAv/DcKz2nd9dFdLmGi9aZrMVMmuYw6F8FwA7fb9gpF/4k0NdWzbho6Wyj/8PQU3T07wn9W5AUU4xaCUsl/9qGup+ReEOLPmv8yae0XGAsn3urjf5ljsl6Q/3YtdlMe5w6qvNBvL1dpk0fzWGtA=
  on:
    tags: true
    repo: SpheMakh/Penthesilea
