# This is the driver container
driver:
    build: . 
    ports:
        - "5000:5000"
    volumes:
        - /storage
    volumes_from:
        - data
    links:
        - simms
        - simulator
        - imager


# Creates empty MS using simms
simms:
    build: ./containers/simms
    ports:
        - "5001:50001"
    volumes:
        - .:/code


# Creates empty MS using simms
simulator:
    build: ./containers/meqtrees_sim
    ports:
        - "5002:50002"
    volumes:
        - .:/code


# Creates empty MS using simms
imager:
    build: ./containers/imager
    ports:
        - "5003:50003"
    volumes:
        - .:/code

# This is the storage container
data:
    build: ./containers/data
    volumes:
        - /data
