dray:                                                                                           
  image: centurylink/dray
  links:
   - redis
  environment:
   - LOG_LEVEL="debug
   - REDIS_PORT="6379:6379"
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
   - /tmp:/tmp
   - input:/input
   - storage:/storage
  ports:
   - "3000:3000"
redis:
  image: redis
  ports:
   - "6379:6379"
